# Generated by Django 4.2.3 on 2023-07-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0004_alter_goalcategory_board"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardparticipant",
            options={
                "verbose_name": "Участник доски",
                "verbose_name_plural": "Участники досок",
            },
        ),
    ]
